-- Obsolete AI retrieval compatibility artifact. Active hybrid retrieval is
-- implemented by core migration 000040_ai_knowledge_retrieval.sql.
-- Source: supabase/knowledge.sql
-- Section: knowledge_chunks, vector index, match_knowledge, and read policies.
-- Status: retained for historical bundle compatibility; never applied.
