-- Obsolete AI retrieval compatibility artifact. Active hybrid retrieval is
-- implemented by core migration 000040_ai_knowledge_retrieval.sql.
-- Source: supabase/langchain.sql
-- Section: LangChain checkpoint persistence tables and policies.
-- Status: retained for historical bundle compatibility; never applied.
