-- Obsolete AI retrieval compatibility artifact. Active hybrid retrieval is
-- implemented by core migration 000040_ai_knowledge_retrieval.sql.
-- Source: supabase/security-hardening.sql
-- Section: match_knowledge function hardening.
-- Status: retained for historical bundle compatibility; never applied.
