export type JsonSchema = Record<string, unknown>;

export interface ContractOperation {
  method: "get" | "post" | "put" | "patch";
  path: string;
  operationId: string;
  summary: string;
  tags: string[];
  responseSchema?: string;
  successStatus?: "200" | "201" | "202" | "204";
  querySchema?: string;
  requestBodySchema?: string;
  pathParameters?: string[];
  idempotencyRequired?: boolean;
  moduleGated?: "chat";
  disabledErrorCode?: string;
  authentication?: "public" | "cookie";
}

const ref = (name: string) => ({ $ref: `#/$defs/${name}` });
const stringSchema = { type: "string" };
const booleanSchema = { type: "boolean" };
const positiveIntegerSchema = { type: "integer", minimum: 1 };
const nonNegativeIntegerSchema = { type: "integer", minimum: 0 };
const stringArraySchema = { type: "array", items: stringSchema };

const objectSchema = (
  properties: Record<string, JsonSchema>,
  required: string[] = [],
): JsonSchema => ({
  type: "object",
  properties,
  ...(required.length > 0 ? { required } : {}),
  additionalProperties: false,
});

export const publicJsonSchemaDefinitions: Record<string, JsonSchema> = {
  JsonPrimitive: {
    oneOf: [
      stringSchema,
      { type: "number" },
      booleanSchema,
      { type: "null" },
    ],
  },
  JsonValue: {
    oneOf: [
      ref("JsonPrimitive"),
      { type: "array", items: ref("JsonValue") },
      { type: "object", additionalProperties: ref("JsonValue") },
    ],
  },
  MetadataValue: ref("JsonPrimitive"),
  MetadataRecord: {
    type: "object",
    additionalProperties: ref("MetadataValue"),
  },
  RequestContext: objectSchema({
    tenant_id: stringSchema,
    venue_id: stringSchema,
    correlation_id: stringSchema,
  }),
  PlatformUserRole: {
    type: "string",
    enum: ["owner", "staff"],
  },
  SetupStatusResponse: objectSchema({
    setup_available: booleanSchema,
  }, ["setup_available"]),
  CreateFirstOwnerInput: objectSchema({
    setup_token: { type: "string", minLength: 43, maxLength: 128 },
    email: { type: "string", format: "email", maxLength: 320 },
    display_name: { type: "string", minLength: 1, maxLength: 120 },
    password: { type: "string", minLength: 12, maxLength: 128 },
  }, ["setup_token", "email", "display_name", "password"]),
  LoginInput: objectSchema({
    email: { type: "string", format: "email", maxLength: 320 },
    password: { type: "string", minLength: 1, maxLength: 128 },
  }, ["email", "password"]),
  AuthenticatedSessionResponse: objectSchema({
    user_id: { type: "string", format: "uuid" },
    tenant_id: { type: "string", minLength: 1 },
    role: ref("PlatformUserRole"),
    venue_ids: { type: "array", items: { type: "string", format: "uuid" } },
    expires_at: { type: "string", format: "date-time" },
  }, ["user_id", "tenant_id", "role", "venue_ids", "expires_at"]),
  StaffInvitationInput: objectSchema({
    email: { type: "string", format: "email", maxLength: 320 },
    display_name: { type: "string", minLength: 1, maxLength: 120 },
    venue_ids: { type: "array", minItems: 1, items: { type: "string", format: "uuid" } },
  }, ["email", "display_name", "venue_ids"]),
  StaffInvitationResponse: objectSchema({
    user_id: { type: "string", format: "uuid" },
    invitation_token: { type: "string", minLength: 43, maxLength: 128 },
    expires_at: { type: "string", format: "date-time" },
  }, ["user_id", "invitation_token", "expires_at"]),
  StaffMemberResponse: objectSchema({
    user_id: { type: "string", format: "uuid" },
    email: { type: "string", format: "email", maxLength: 320 },
    display_name: { type: "string", minLength: 1, maxLength: 120 },
    status: { type: "string", enum: ["invited", "active", "disabled"] },
    venue_ids: { type: "array", items: { type: "string", format: "uuid" } },
  }, ["user_id", "email", "display_name", "status", "venue_ids"]),
  ListStaffResponse: objectSchema({
    staff: { type: "array", items: ref("StaffMemberResponse") },
  }, ["staff"]),
  StaffAccessPatch: objectSchema({
    status: { type: "string", enum: ["active", "disabled"] },
    venue_ids: { type: "array", minItems: 1, items: { type: "string", format: "uuid" } },
  }, ["venue_ids"]),
  AcceptStaffInvitationInput: objectSchema({
    display_name: { type: "string", minLength: 1, maxLength: 120 },
    password: { type: "string", minLength: 12, maxLength: 128 },
  }, ["display_name", "password"]),
  RequestPasswordResetInput: objectSchema({
    email: { type: "string", format: "email", maxLength: 320 },
  }, ["email"]),
  CompletePasswordResetInput: objectSchema({
    password: { type: "string", minLength: 12, maxLength: 128 },
  }, ["password"]),
  InstallationLocationInput: objectSchema({
    name: { type: "string", minLength: 1, maxLength: 120 },
    address: { type: "string", maxLength: 500 },
    timezone: { type: "string", minLength: 1, maxLength: 100 },
  }, ["name", "timezone"]),
  InstallationBusinessInput: objectSchema({
    name: { type: "string", minLength: 1, maxLength: 120 },
    public_slug: { type: "string", minLength: 1, maxLength: 120 },
    timezone: { type: "string", minLength: 1, maxLength: 100 },
    location: objectSchema({
      name: { type: "string", minLength: 1, maxLength: 120 },
      address: { type: "string", maxLength: 500 },
    }, ["name"]),
  }, ["name", "public_slug", "timezone", "location"]),
  InstallationLocationPatch: {
    ...objectSchema({
      name: { type: "string", minLength: 1, maxLength: 120 },
      address: { oneOf: [{ type: "string", maxLength: 500 }, { type: "null" }] },
      timezone: { type: "string", minLength: 1, maxLength: 100 },
    }),
    minProperties: 1,
  },
  InstallationLocationResponse: objectSchema({
    location_id: { type: "string", format: "uuid" },
    name: { type: "string", minLength: 1 },
    address: stringSchema,
    timezone: { type: "string", minLength: 1 },
  }, ["location_id", "name", "timezone"]),
  ListInstallationLocationsResponse: objectSchema({
    locations: { type: "array", items: ref("InstallationLocationResponse") },
  }, ["locations"]),
  MetadataResponse: objectSchema({
    api_version: stringSchema,
    modules: stringArraySchema,
    compatibility: objectSchema({
      sdk_versions: stringArraySchema,
      contract_types_versions: stringArraySchema,
      notices: stringArraySchema,
    }),
  }, ["api_version", "modules"]),
  TenantResponse: objectSchema({
    tenant_id: stringSchema,
    name: stringSchema,
    default_venue_id: stringSchema,
    metadata: ref("MetadataRecord"),
  }, ["tenant_id"]),
  ListVenuesQuery: objectSchema({
    tenant_id: stringSchema,
    include_inactive: booleanSchema,
  }),
  VenueResponse: objectSchema({
    venue_id: stringSchema,
    tenant_id: stringSchema,
    name: stringSchema,
    timezone: stringSchema,
    metadata: ref("MetadataRecord"),
  }, ["venue_id", "name"]),
  ListVenuesResponse: objectSchema({
    venues: { type: "array", items: ref("VenueResponse") },
  }, ["venues"]),
  ListServicesQuery: objectSchema({
    venue_id: stringSchema,
    include_inactive: booleanSchema,
  }),
  ResourceKind: {
    type: "string",
    enum: ["seat", "station", "room", "court", "screening", "capacity_bucket", "custom"],
  },
  ResourceStrategy: {
    type: "string",
    enum: ["quantity", "assigned_resource", "hybrid"],
  },
  ResourceResponse: objectSchema({
    resource_id: stringSchema,
    service_id: stringSchema,
    label: stringSchema,
    kind: ref("ResourceKind"),
    is_active: booleanSchema,
    capacity: nonNegativeIntegerSchema,
    metadata: ref("MetadataRecord"),
  }, ["resource_id", "label", "kind", "is_active"]),
  ResourceLayoutResource: objectSchema({
    resource_id: stringSchema,
    label: stringSchema,
    row: { type: "integer" },
    column: { type: "integer" },
    x: { type: "number" },
    y: { type: "number" },
    width: { type: "number", exclusiveMinimum: 0 },
    height: { type: "number", exclusiveMinimum: 0 },
    metadata: ref("MetadataRecord"),
  }, ["resource_id"]),
  ResourceLayoutResponse: objectSchema({
    layout_id: stringSchema,
    service_id: stringSchema,
    kind: { type: "string", enum: ["none", "grid", "custom"] },
    resources: { type: "array", items: ref("ResourceLayoutResource") },
    metadata: ref("MetadataRecord"),
  }, ["layout_id", "kind"]),
  ServiceResponse: objectSchema({
    service_id: stringSchema,
    venue_id: stringSchema,
    name: stringSchema,
    is_active: booleanSchema,
    description: stringSchema,
    duration_minutes: positiveIntegerSchema,
    total_quantity: nonNegativeIntegerSchema,
    resource_kind: ref("ResourceKind"),
    resource_strategy: ref("ResourceStrategy"),
    reservation_policy: ref("JsonValue"),
    resources: { type: "array", items: ref("ResourceResponse") },
    layout: ref("ResourceLayoutResponse"),
    metadata: ref("MetadataRecord"),
  }, ["service_id", "name"]),
  ExperienceServiceInput: objectSchema({
    name: { type: "string", minLength: 1, maxLength: 120 },
    description: { type: "string", maxLength: 1000 },
    duration_minutes: { type: "integer", minimum: 1, maximum: 1440 },
    total_quantity: { type: "integer", minimum: 1, maximum: 10000 },
    resource_kind: ref("ResourceKind"),
    resource_strategy: ref("ResourceStrategy"),
  }, ["name", "duration_minutes", "total_quantity", "resource_kind", "resource_strategy"]),
  ExperienceResourceInput: objectSchema({
    service_id: stringSchema,
    label: { type: "string", minLength: 1, maxLength: 120 },
    kind: ref("ResourceKind"),
    capacity: { type: "integer", minimum: 1, maximum: 10000 },
  }, ["service_id", "label", "kind", "capacity"]),
  ArchiveCatalogItemInput: objectSchema({
    reason: { type: "string", maxLength: 500 },
  }),
  ExperienceOperatingInterval: objectSchema({
    day_of_week: { type: "integer", minimum: 0, maximum: 6 },
    start_time: { type: "string", pattern: "^(?:[01]\\d|2[0-3]):[0-5]\\d$" },
    end_time: { type: "string", pattern: "^(?:[01]\\d|2[0-3]):[0-5]\\d$" },
  }, ["day_of_week", "start_time", "end_time"]),
  ExperienceDateClosure: objectSchema({
    date: { type: "string", pattern: "^\\d{4}-\\d{2}-\\d{2}$" },
    reason: { type: "string", maxLength: 200 },
  }, ["date"]),
  ExperienceOperatingHoursInput: objectSchema({
    timezone: { type: "string", minLength: 1, maxLength: 100 },
    booking_horizon_days: { type: "integer", minimum: 1, maximum: 365 },
    slot_interval_minutes: { type: "integer", minimum: 5, maximum: 720 },
    minimum_notice_minutes: { type: "integer", minimum: 0, maximum: 10080 },
    intervals: { type: "array", maxItems: 56, items: ref("ExperienceOperatingInterval") },
    closures: { type: "array", maxItems: 366, items: ref("ExperienceDateClosure") },
  }, ["timezone", "booking_horizon_days", "slot_interval_minutes", "minimum_notice_minutes", "intervals", "closures"]),
  ExperienceOperatingHoursResponse: objectSchema({
    tenant_id: stringSchema,
    venue_id: stringSchema,
    timezone: { type: "string", minLength: 1, maxLength: 100 },
    booking_horizon_days: { type: "integer", minimum: 1, maximum: 365 },
    slot_interval_minutes: { type: "integer", minimum: 5, maximum: 720 },
    minimum_notice_minutes: { type: "integer", minimum: 0, maximum: 10080 },
    intervals: { type: "array", maxItems: 56, items: ref("ExperienceOperatingInterval") },
    closures: { type: "array", maxItems: 366, items: ref("ExperienceDateClosure") },
    updated_at: stringSchema,
  }, ["tenant_id", "venue_id", "timezone", "booking_horizon_days", "slot_interval_minutes", "minimum_notice_minutes", "intervals", "closures"]),
  ExperienceKnowledgeInput: objectSchema({
    question: { type: "string", minLength: 1, maxLength: 300 },
    answer: { type: "string", minLength: 1, maxLength: 4000 },
    source: { type: "string", maxLength: 500 },
  }, ["question", "answer"]),
  ExperienceKnowledgeEntryResponse: objectSchema({
    knowledge_id: stringSchema,
    tenant_id: stringSchema,
    venue_id: stringSchema,
    question: { type: "string", minLength: 1, maxLength: 300 },
    answer: { type: "string", minLength: 1, maxLength: 4000 },
    source: { type: "string", maxLength: 500 },
    status: { type: "string", enum: ["active", "archived"] },
    created_at: stringSchema,
    updated_at: stringSchema,
  }, ["knowledge_id", "tenant_id", "venue_id", "question", "answer", "status"]),
  ListExperienceKnowledgeResponse: objectSchema({
    entries: { type: "array", items: ref("ExperienceKnowledgeEntryResponse") },
  }, ["entries"]),
  ExperienceChannelReadiness: objectSchema({
    desired_enabled: booleanSchema,
    configured: booleanSchema,
    ready: booleanSchema,
    state: { type: "string", enum: ["ready", "not_configured", "degraded"] },
    message: stringSchema,
  }, ["desired_enabled", "configured", "ready", "state"]),
  ExperienceChannelSettingsResponse: objectSchema({
    channels: ref("ExperienceChannels"),
    readiness: objectSchema({
      web_booking: ref("ExperienceChannelReadiness"),
      web_chat: ref("ExperienceChannelReadiness"),
      whatsapp: ref("ExperienceChannelReadiness"),
    }, ["web_booking", "web_chat", "whatsapp"]),
  }, ["channels", "readiness"]),
  OperationsReservationChannel: { type: "string", enum: ["web_booking", "web_chat", "whatsapp", "simulation"] },
  OperationsTimelineReservation: objectSchema({
    reservation_id: stringSchema,
    service_name: stringSchema,
    customer_name: stringSchema,
    start_time: stringSchema,
    end_time: stringSchema,
    quantity: nonNegativeIntegerSchema,
    status: stringSchema,
    channel: ref("OperationsReservationChannel"),
  }, ["reservation_id", "service_name", "customer_name", "start_time", "end_time", "quantity", "status", "channel"]),
  OperationsOverviewResponse: objectSchema({
    generated_at: stringSchema,
    timezone: stringSchema,
    local_date: stringSchema,
    reservations: objectSchema({
      today: nonNegativeIntegerSchema, pending: nonNegativeIntegerSchema, confirmed: nonNegativeIntegerSchema, completed: nonNegativeIntegerSchema, cancelled: nonNegativeIntegerSchema,
      timeline: { type: "array", items: ref("OperationsTimelineReservation"), maxItems: 20 },
    }, ["today", "pending", "confirmed", "completed", "cancelled", "timeline"]),
    resources: objectSchema({ total: nonNegativeIntegerSchema, available: nonNegativeIntegerSchema, maintenance: nonNegativeIntegerSchema }, ["total", "available", "maintenance"]),
    conversations: objectSchema({ open: nonNegativeIntegerSchema, staff_takeover: nonNegativeIntegerSchema }, ["open", "staff_takeover"]),
    channel_readiness: objectSchema({
      web_booking: ref("ExperienceChannelReadiness"), web_chat: ref("ExperienceChannelReadiness"), whatsapp: ref("ExperienceChannelReadiness"),
    }, ["web_booking", "web_chat", "whatsapp"]),
  }, ["generated_at", "timezone", "local_date", "reservations", "resources", "conversations", "channel_readiness"]),
  AnalyticsQuery: objectSchema({ from: stringSchema, to: stringSchema, include_simulation: booleanSchema }, ["from", "to"]),
  AnalyticsResponse: objectSchema({
    generated_at: stringSchema, timezone: stringSchema, from_date: stringSchema, to_date: stringSchema, include_simulation: booleanSchema,
    totals: objectSchema({ reservations: nonNegativeIntegerSchema, cancelled: nonNegativeIntegerSchema, cancellation_rate: { type: "number", minimum: 0, maximum: 1 } }, ["reservations", "cancelled", "cancellation_rate"]),
    reservations_by_day: { type: "array", maxItems: 366, items: objectSchema({ date: stringSchema, total: nonNegativeIntegerSchema, confirmed: nonNegativeIntegerSchema, completed: nonNegativeIntegerSchema, cancelled: nonNegativeIntegerSchema }, ["date", "total", "confirmed", "completed", "cancelled"]) },
    reservations_by_status: { type: "array", maxItems: 20, items: objectSchema({ status: stringSchema, count: nonNegativeIntegerSchema }, ["status", "count"]) },
    reservations_by_channel: { type: "array", maxItems: 4, items: objectSchema({ channel: ref("OperationsReservationChannel"), count: nonNegativeIntegerSchema }, ["channel", "count"]) },
    channel_performance: { type: "array", maxItems: 3, items: objectSchema({ channel: ref("ConversationChannel"), conversations_started: nonNegativeIntegerSchema, proposal_shown: nonNegativeIntegerSchema, confirmation_requested: nonNegativeIntegerSchema, reservations_created: nonNegativeIntegerSchema, conversion_rate: { type: "number", minimum: 0, maximum: 1 } }, ["channel", "conversations_started", "proposal_shown", "confirmation_requested", "reservations_created", "conversion_rate"]) },
    reservations_by_service: { type: "array", maxItems: 20, items: objectSchema({ service_id: stringSchema, service_name: stringSchema, count: nonNegativeIntegerSchema }, ["service_id", "service_name", "count"]) },
    popular_slots: { type: "array", maxItems: 20, items: objectSchema({ day_of_week: { type: "integer", minimum: 1, maximum: 7 }, start_time: stringSchema, count: nonNegativeIntegerSchema }, ["day_of_week", "start_time", "count"]) },
    funnel: objectSchema({ conversations_started: nonNegativeIntegerSchema, proposal_shown: nonNegativeIntegerSchema, confirmation_requested: nonNegativeIntegerSchema, reservations_created: nonNegativeIntegerSchema }, ["conversations_started", "proposal_shown", "confirmation_requested", "reservations_created"]),
    automation: objectSchema({ automated_conversations: nonNegativeIntegerSchema, staff_takeovers: nonNegativeIntegerSchema, containment_rate: { type: "number", minimum: 0, maximum: 1 }, takeover_rate: { type: "number", minimum: 0, maximum: 1 } }, ["automated_conversations", "staff_takeovers", "containment_rate", "takeover_rate"]),
  }, ["generated_at", "timezone", "from_date", "to_date", "include_simulation", "totals", "reservations_by_day", "reservations_by_status", "reservations_by_channel", "channel_performance", "reservations_by_service", "popular_slots", "funnel", "automation"]),
  ConversationChannel: { type: "string", enum: ["web_chat", "whatsapp", "simulation"] },
  ConversationAutomationState: { type: "string", enum: ["automated", "manual"] },
  ConversationDeliveryState: { type: "string", enum: ["pending", "sent", "delivered", "failed"] },
  ConversationParticipantResponse: objectSchema({
    participant_id: stringSchema,
    role: { type: "string", enum: ["customer", "staff", "automation"] },
    display_name: stringSchema,
    contact_hint: stringSchema,
  }, ["participant_id", "role"]),
  ConversationResponse: objectSchema({
    conversation_id: stringSchema,
    tenant_id: stringSchema,
    venue_id: stringSchema,
    channel: ref("ConversationChannel"),
    status: { type: "string", enum: ["active", "closed"] },
    automation_state: ref("ConversationAutomationState"),
    participant: ref("ConversationParticipantResponse"),
    reservation_id: stringSchema,
    last_message_at: stringSchema,
    created_at: stringSchema,
    updated_at: stringSchema,
  }, ["conversation_id", "tenant_id", "venue_id", "channel", "status", "automation_state", "created_at", "updated_at"]),
  ConversationMessageResponse: objectSchema({
    message_id: stringSchema,
    conversation_id: stringSchema,
    channel: ref("ConversationChannel"),
    direction: { type: "string", enum: ["inbound", "outbound"] },
    sender_type: { type: "string", enum: ["customer", "automation", "staff", "system"] },
    delivery_state: ref("ConversationDeliveryState"),
    content: stringSchema,
    reservation_id: stringSchema,
    created_at: stringSchema,
  }, ["message_id", "conversation_id", "channel", "direction", "sender_type", "delivery_state", "content", "created_at"]),
  ListConversationsQuery: objectSchema({
    channel: ref("ConversationChannel"),
    status: { type: "string", enum: ["active", "closed"] },
    limit: { type: "integer", minimum: 1, maximum: 100 },
  }),
  ListConversationsResponse: objectSchema({ conversations: { type: "array", items: ref("ConversationResponse") } }, ["conversations"]),
  ListConversationMessagesQuery: objectSchema({ before: stringSchema, limit: { type: "integer", minimum: 1, maximum: 100 } }),
  ListConversationMessagesResponse: objectSchema({
    messages: { type: "array", items: ref("ConversationMessageResponse") },
    next_cursor: stringSchema,
  }, ["messages"]),
  ConversationAutomationInput: objectSchema({ automation_state: ref("ConversationAutomationState") }, ["automation_state"]),
  ConversationStaffReplyInput: objectSchema({ content: stringSchema }, ["content"]),
  PublicChatMessageInput: objectSchema({
    thread_id: stringSchema,
    external_message_id: stringSchema,
    content: stringSchema,
    display_name: stringSchema,
  }, ["thread_id", "content"]),
  ConversationBookingProposalResponse: objectSchema({
    proposal_id: stringSchema,
    service_id: stringSchema,
    service_name: stringSchema,
    date: stringSchema,
    start_time: stringSchema,
    end_time: stringSchema,
    quantity: positiveIntegerSchema,
  }, ["proposal_id", "service_id", "service_name", "date", "start_time", "end_time", "quantity"]),
  PublicChatConversationResponse: objectSchema({
    conversation_id: stringSchema,
    automation_state: ref("ConversationAutomationState"),
    message: ref("ConversationMessageResponse"),
    proposal: ref("ConversationBookingProposalResponse"),
    reservation: ref("ReservationResponse"),
    automation_suppressed: booleanSchema,
  }, ["conversation_id", "automation_state"]),
  PublicChatConfirmationInput: objectSchema({ proposal_id: stringSchema }, ["proposal_id"]),
  ListServicesResponse: objectSchema({
    services: { type: "array", items: ref("ServiceResponse") },
  }, ["services"]),
  ListResourcesQuery: objectSchema({
    venue_id: stringSchema,
    service_id: stringSchema,
    include_inactive: booleanSchema,
  }),
  ListResourcesResponse: objectSchema({
    resources: { type: "array", items: ref("ResourceResponse") },
  }, ["resources"]),
  AvailabilityQuery: objectSchema({
    venue_id: stringSchema,
    service_id: stringSchema,
    date: stringSchema,
    start_at: stringSchema,
    end_at: stringSchema,
    quantity: positiveIntegerSchema,
    resource_ids: stringArraySchema,
    staff_id: { type: "string", format: "uuid" },
  }, ["service_id"]),
  AvailabilitySlot: objectSchema({
    start_at: stringSchema,
    end_at: stringSchema,
    start_time: stringSchema,
    end_time: stringSchema,
    available_quantity: nonNegativeIntegerSchema,
    is_available: booleanSchema,
    resource_ids: stringArraySchema,
    taken_resource_labels: stringArraySchema,
    maintenance_resource_labels: stringArraySchema,
    staff_id: { type: "string", format: "uuid" },
  }, ["available_quantity", "is_available"]),
  AvailabilityResponse: objectSchema({
    slots: { type: "array", items: ref("AvailabilitySlot") },
    total_quantity: nonNegativeIntegerSchema,
    resource_kind: ref("ResourceKind"),
    resource_strategy: ref("ResourceStrategy"),
    reservation_policy: ref("JsonValue"),
    resources: { type: "array", items: ref("ResourceResponse") },
    layout: ref("ResourceLayoutResponse"),
  }, ["slots"]),
  CustomerSnapshot: objectSchema({
    customer_id: stringSchema,
    external_customer_id: stringSchema,
    name: stringSchema,
    email: stringSchema,
    phone: stringSchema,
    locale: stringSchema,
    metadata: ref("MetadataRecord"),
  }),
  ReservationItemInput: objectSchema({
    resource_id: stringSchema,
    resource_label: stringSchema,
    quantity: positiveIntegerSchema,
  }, ["quantity"]),
  PaymentReference: objectSchema({
    payment_reference_id: stringSchema,
    provider: stringSchema,
    status: stringSchema,
    metadata: ref("MetadataRecord"),
  }),
  CreateReservationInput: objectSchema({
    tenant_id: stringSchema,
    venue_id: stringSchema,
    service_id: stringSchema,
    start_at: stringSchema,
    end_at: stringSchema,
    date: stringSchema,
    start_time: stringSchema,
    end_time: stringSchema,
    quantity: positiveIntegerSchema,
    resource_ids: stringArraySchema,
    staff_id: { type: "string", format: "uuid" },
    reservation_items: { type: "array", items: ref("ReservationItemInput") },
    customer: ref("CustomerSnapshot"),
    source: stringSchema,
    metadata: ref("MetadataRecord"),
    payment_reference: ref("PaymentReference"),
  }, ["service_id", "quantity", "customer"]),
  ReservationResponse: objectSchema({
    reservation_id: stringSchema,
    status: stringSchema,
    tenant_id: stringSchema,
    venue_id: stringSchema,
    service_id: stringSchema,
    staff_id: { type: "string", format: "uuid" },
    start_at: stringSchema,
    end_at: stringSchema,
    date: stringSchema,
    start_time: stringSchema,
    end_time: stringSchema,
    quantity: positiveIntegerSchema,
    reservation_items: { type: "array", items: ref("ReservationItemInput") },
    customer: ref("CustomerSnapshot"),
    payment_reference: ref("PaymentReference"),
    metadata: ref("MetadataRecord"),
    created_at: stringSchema,
    updated_at: stringSchema,
    management_token: stringSchema,
    management_expires_at: stringSchema,
  }, ["reservation_id", "status", "service_id", "quantity"]),
  ListReservationsQuery: objectSchema({
    tenant_id: stringSchema,
    venue_id: stringSchema,
    service_id: stringSchema,
    status: stringSchema,
    customer_id: stringSchema,
    search: stringSchema,
    start_at: stringSchema,
    end_at: stringSchema,
  }),
  ReservationListSummary: objectSchema({
    total: nonNegativeIntegerSchema,
    confirmed_today: nonNegativeIntegerSchema,
  }),
  ListReservationsResponse: objectSchema({
    reservations: { type: "array", items: ref("ReservationResponse") },
    summary: ref("ReservationListSummary"),
  }, ["reservations"]),
  UpdateReservationPatch: objectSchema({
    customer: ref("CustomerSnapshot"),
    notes: stringSchema,
    metadata: ref("MetadataRecord"),
    status: stringSchema,
    source: stringSchema,
    payment_reference: ref("PaymentReference"),
  }),
  CancelReservationInput: objectSchema({
    reason: stringSchema,
    metadata: ref("MetadataRecord"),
  }),
  RescheduleReservationInput: objectSchema({
    start_at: stringSchema,
    end_at: stringSchema,
    date: stringSchema,
    start_time: stringSchema,
    end_time: stringSchema,
    quantity: positiveIntegerSchema,
    resource_ids: stringArraySchema,
    reservation_items: { type: "array", items: ref("ReservationItemInput") },
    metadata: ref("MetadataRecord"),
  }),
  RescheduleManagedReservationInput: objectSchema({
    date: { type: "string", format: "date" },
    start_time: { type: "string", pattern: "^(?:[01]\\d|2[0-3]):[0-5]\\d$" },
    staff_id: { type: "string", format: "uuid" },
  }, ["date", "start_time", "staff_id"]),
  ListResourceMaintenanceQuery: objectSchema({
    venue_id: stringSchema,
    service_id: stringSchema,
    resource_id: stringSchema,
    active_only: booleanSchema,
  }),
  ResourceMaintenanceResponse: objectSchema({
    maintenance_id: stringSchema,
    resource_id: stringSchema,
    service_id: stringSchema,
    starts_at: stringSchema,
    ends_at: stringSchema,
    reason: stringSchema,
    metadata: ref("MetadataRecord"),
  }, ["maintenance_id"]),
  ListResourceMaintenanceResponse: objectSchema({
    maintenance: { type: "array", items: ref("ResourceMaintenanceResponse") },
  }, ["maintenance"]),
  CreateResourceMaintenanceInput: objectSchema({
    resource_id: stringSchema,
    service_id: stringSchema,
    starts_at: stringSchema,
    ends_at: stringSchema,
    reason: stringSchema,
    metadata: ref("MetadataRecord"),
  }),
  EndResourceMaintenanceInput: objectSchema({
    ended_at: stringSchema,
    reason: stringSchema,
    metadata: ref("MetadataRecord"),
  }),
  PlatformErrorCode: {
    anyOf: [
      {
        type: "string",
        enum: [
          "bad_request",
          "unauthorized",
          "forbidden",
          "not_found",
          "conflict",
          "validation_failed",
          "missing_idempotency_key",
          "idempotency_key_reused_with_different_request",
          "idempotency_replay_unavailable",
          "chat_module_disabled",
          "whatsapp_module_disabled",
          "internal_error",
          "rate_limited",
          "payload_too_large",
        ],
      },
      { type: "string" },
    ],
    description: "Stable machine-readable platform error code. The enum lists codes defined by this release; compatible extensions remain valid strings.",
  },
  IdempotencyMetadata: objectSchema({
    key: stringSchema,
    status: { type: "string", enum: ["created", "replayed", "rejected"] },
    replayed: booleanSchema,
  }),
  PlatformErrorBody: objectSchema({
    code: ref("PlatformErrorCode"),
    message: stringSchema,
    status: { type: "integer" },
    request_id: stringSchema,
    details: ref("JsonValue"),
    causes: { type: "array", items: ref("JsonValue") },
    retryable: booleanSchema,
    idempotency: ref("IdempotencyMetadata"),
    documentation_url: stringSchema,
  }, ["code", "message", "status"]),
  PlatformErrorResponse: objectSchema({
    error: ref("PlatformErrorBody"),
  }, ["error"]),
  ChatCreateReservationSessionInput: objectSchema({
    customer: ref("CustomerSnapshot"),
    service_id: stringSchema,
    venue_id: stringSchema,
    metadata: ref("MetadataRecord"),
  }),
  ChatSessionResponse: objectSchema({
    chat_session_id: stringSchema,
    status: stringSchema,
    metadata: ref("MetadataRecord"),
  }, ["chat_session_id", "status"]),
  ChatMessageInput: objectSchema({
    message: stringSchema,
    metadata: ref("MetadataRecord"),
  }, ["message"]),
  ChatMessageResponse: objectSchema({
    chat_session_id: stringSchema,
    message_id: stringSchema,
    content: stringSchema,
    actions: { type: "array", items: ref("JsonValue") },
    reservation: ref("ReservationResponse"),
    metadata: ref("MetadataRecord"),
  }, ["chat_session_id"]),
  ChatConfirmReservationInput: objectSchema({
    reservation_intent_id: stringSchema,
    metadata: ref("MetadataRecord"),
  }),
  ExperiencePresetId: {
    type: "string",
    enum: ["racing_gaming", "rooms_facilities", "appointments_salon", "sports_courts", "restaurant_tables", "cinema_events", "equipment_rental", "classes_workshops"],
  },
  ExperienceConfigurationState: {
    type: "string",
    enum: ["draft", "published", "archived"],
  },
  ExperienceBranding: objectSchema({
    brand_name: stringSchema,
    primary_color: { type: "string", pattern: "^#[0-9a-fA-F]{6}$" },
    secondary_color: { type: "string", pattern: "^#[0-9a-fA-F]{6}$" },
    logo_url: { type: "string", format: "uri" },
    description: stringSchema,
  }, ["brand_name"]),
  ExperienceTerminology: objectSchema({
    customer: stringSchema,
    resource: stringSchema,
    booking: stringSchema,
  }, ["customer", "resource", "booking"]),
  ExperienceChannels: objectSchema({
    web_booking: booleanSchema,
    web_chat: booleanSchema,
    whatsapp: booleanSchema,
  }, ["web_booking", "web_chat", "whatsapp"]),
  ExperiencePresetSummary: objectSchema({
    preset_id: ref("ExperiencePresetId"),
    name: stringSchema,
    description: stringSchema,
    resource_strategy: ref("ResourceStrategy"),
    terminology: ref("ExperienceTerminology"),
  }, ["preset_id", "name", "description", "resource_strategy", "terminology"]),
  ListExperiencePresetsResponse: objectSchema({
    presets: { type: "array", items: ref("ExperiencePresetSummary") },
  }, ["presets"]),
  BusinessProfileResponse: objectSchema({
    business_id: stringSchema,
    tenant_id: stringSchema,
    venue_id: stringSchema,
    name: stringSchema,
    public_slug: stringSchema,
    preset_id: ref("ExperiencePresetId"),
    status: { type: "string", enum: ["draft", "published", "archived"] },
  }, ["business_id", "tenant_id", "venue_id", "name", "public_slug", "preset_id", "status"]),
  InstallationBusinessResponse: objectSchema({
    profile: ref("BusinessProfileResponse"),
    locations: { type: "array", minItems: 1, items: ref("InstallationLocationResponse") },
  }, ["profile", "locations"]),
  ExperienceConfigurationResponse: objectSchema({
    configuration_id: stringSchema,
    business_id: stringSchema,
    version: positiveIntegerSchema,
    state: ref("ExperienceConfigurationState"),
    preset_id: ref("ExperiencePresetId"),
    branding: ref("ExperienceBranding"),
    terminology: ref("ExperienceTerminology"),
    channels: ref("ExperienceChannels"),
    updated_at: stringSchema,
    published_at: stringSchema,
  }, ["configuration_id", "business_id", "version", "state", "preset_id", "branding", "terminology", "channels", "updated_at"]),
  ExperienceDraftInput: objectSchema({
    preset_id: ref("ExperiencePresetId"),
    branding: ref("ExperienceBranding"),
    terminology: ref("ExperienceTerminology"),
    channels: ref("ExperienceChannels"),
  }, ["preset_id", "branding", "terminology", "channels"]),
  ExperienceIdentityInput: objectSchema({
    name: { type: "string", minLength: 1, maxLength: 120 },
    public_slug: { type: "string", pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$" },
    branding: ref("ExperienceBranding"),
    terminology: ref("ExperienceTerminology"),
  }, ["name", "public_slug", "branding", "terminology"]),
  PublishExperienceInput: objectSchema({
    configuration_id: stringSchema,
  }, ["configuration_id"]),
  ExperienceWorkspaceResponse: objectSchema({
    profile: ref("BusinessProfileResponse"),
    draft: ref("ExperienceConfigurationResponse"),
    published: ref("ExperienceConfigurationResponse"),
  }, ["profile"]),
  ExperienceValidationIssue: objectSchema({
    path: stringSchema,
    message: stringSchema,
  }, ["path", "message"]),
  ExperienceValidationResponse: objectSchema({
    valid: booleanSchema,
    issues: { type: "array", items: ref("ExperienceValidationIssue") },
  }, ["valid", "issues"]),
  PublicBusinessProfileResponse: objectSchema({
    business_id: stringSchema,
    name: stringSchema,
    public_slug: stringSchema,
    preset_id: ref("ExperiencePresetId"),
  }, ["business_id", "name", "public_slug", "preset_id"]),
  PublicExperienceResponse: objectSchema({
    profile: ref("PublicBusinessProfileResponse"),
    configuration: {
      allOf: [
        ref("ExperienceConfigurationResponse"),
        objectSchema({ state: { type: "string", const: "published" } }, ["state"]),
      ],
    },
  }, ["profile", "configuration"]),
};

export const publicContractOperations: ContractOperation[] = [
  {
    method: "get",
    path: "/v1/setup/status",
    operationId: "getSetupStatus",
    summary: "Check whether first-owner setup is available.",
    tags: ["Authentication"],
    responseSchema: "SetupStatusResponse",
    authentication: "public",
  },
  {
    method: "post",
    path: "/v1/setup/owner",
    operationId: "createFirstOwner",
    summary: "Create the installation's first owner.",
    tags: ["Authentication"],
    requestBodySchema: "CreateFirstOwnerInput",
    responseSchema: "AuthenticatedSessionResponse",
    successStatus: "201",
    authentication: "public",
  },
  {
    method: "post",
    path: "/v1/auth/login",
    operationId: "login",
    summary: "Create an owner or staff session.",
    tags: ["Authentication"],
    requestBodySchema: "LoginInput",
    responseSchema: "AuthenticatedSessionResponse",
    authentication: "public",
  },
  {
    method: "post",
    path: "/v1/auth/logout",
    operationId: "logout",
    summary: "Revoke the current session.",
    tags: ["Authentication"],
    successStatus: "204",
    authentication: "cookie",
  },
  {
    method: "get",
    path: "/v1/auth/session",
    operationId: "getSession",
    summary: "Read the current authenticated session.",
    tags: ["Authentication"],
    responseSchema: "AuthenticatedSessionResponse",
    authentication: "cookie",
  },
  {
    method: "post",
    path: "/v1/auth/staff/invitations",
    operationId: "inviteStaff",
    summary: "Invite a staff user to assigned venues.",
    tags: ["Authentication"],
    requestBodySchema: "StaffInvitationInput",
    responseSchema: "StaffInvitationResponse",
    successStatus: "201",
    authentication: "cookie",
  },
  {
    method: "get",
    path: "/v1/auth/staff",
    operationId: "listStaff",
    summary: "List staff users and location assignments.",
    tags: ["Authentication"],
    responseSchema: "ListStaffResponse",
    authentication: "cookie",
  },
  {
    method: "patch",
    path: "/v1/auth/staff/{userId}",
    operationId: "updateStaffAccess",
    summary: "Update a staff user's status and assigned locations.",
    tags: ["Authentication"],
    pathParameters: ["userId"],
    requestBodySchema: "StaffAccessPatch",
    responseSchema: "StaffMemberResponse",
    authentication: "cookie",
  },
  {
    method: "post",
    path: "/v1/auth/staff/invitations/{token}/accept",
    operationId: "acceptStaffInvitation",
    summary: "Accept a single-use staff invitation.",
    tags: ["Authentication"],
    pathParameters: ["token"],
    requestBodySchema: "AcceptStaffInvitationInput",
    responseSchema: "AuthenticatedSessionResponse",
    authentication: "public",
  },
  {
    method: "post",
    path: "/v1/auth/password-reset",
    operationId: "requestPasswordReset",
    summary: "Request a password reset without revealing account existence.",
    tags: ["Authentication"],
    requestBodySchema: "RequestPasswordResetInput",
    successStatus: "202",
    authentication: "public",
  },
  {
    method: "post",
    path: "/v1/auth/password-reset/{token}/complete",
    operationId: "completePasswordReset",
    summary: "Complete a single-use password reset.",
    tags: ["Authentication"],
    pathParameters: ["token"],
    requestBodySchema: "CompletePasswordResetInput",
    successStatus: "204",
    authentication: "public",
  },
  {
    method: "get",
    path: "/v1/installation/business",
    operationId: "getInstallationBusiness",
    summary: "Read the installation business and locations.",
    tags: ["Onboarding"],
    responseSchema: "InstallationBusinessResponse",
    authentication: "cookie",
  },
  {
    method: "put",
    path: "/v1/installation/business",
    operationId: "configureInstallationBusiness",
    summary: "Configure the appointment business and first location.",
    tags: ["Onboarding"],
    requestBodySchema: "InstallationBusinessInput",
    responseSchema: "InstallationBusinessResponse",
    authentication: "cookie",
  },
  {
    method: "get",
    path: "/v1/locations",
    operationId: "listInstallationLocations",
    summary: "List locations visible to the current user.",
    tags: ["Onboarding"],
    responseSchema: "ListInstallationLocationsResponse",
    authentication: "cookie",
  },
  {
    method: "post",
    path: "/v1/locations",
    operationId: "createInstallationLocation",
    summary: "Create an appointment business location.",
    tags: ["Onboarding"],
    requestBodySchema: "InstallationLocationInput",
    responseSchema: "InstallationLocationResponse",
    successStatus: "201",
    authentication: "cookie",
  },
  {
    method: "patch",
    path: "/v1/locations/{location_id}",
    operationId: "updateInstallationLocation",
    summary: "Update an appointment business location.",
    tags: ["Onboarding"],
    pathParameters: ["location_id"],
    requestBodySchema: "InstallationLocationPatch",
    responseSchema: "InstallationLocationResponse",
    authentication: "cookie",
  },
  {
    method: "get",
    path: "/v1/experience/presets",
    operationId: "listExperiencePresets",
    summary: "List the available experience presets.",
    tags: ["Experience Studio"],
    responseSchema: "ListExperiencePresetsResponse",
  },
  {
    method: "get",
    path: "/v1/experience/workspace",
    operationId: "getExperienceWorkspace",
    summary: "Read the current venue experience workspace.",
    tags: ["Experience Studio"],
    responseSchema: "ExperienceWorkspaceResponse",
  },
  {
    method: "get",
    path: "/v1/experience/validation",
    operationId: "validateExperienceWorkspace",
    summary: "Validate every required Studio section",
    tags: ["experience"],
    responseSchema: "ExperienceValidationResponse",
  },
  {
    method: "put",
    path: "/v1/experience/draft",
    operationId: "saveExperienceDraft",
    summary: "Save the current venue experience draft.",
    tags: ["Experience Studio"],
    requestBodySchema: "ExperienceDraftInput",
    responseSchema: "ExperienceWorkspaceResponse",
  },
  {
    method: "get",
    path: "/v1/experience/services",
    operationId: "listExperienceServices",
    summary: "List services in the current venue, including archived entries.",
    tags: ["Experience Studio"],
    responseSchema: "ListServicesResponse",
  },
  {
    method: "post",
    path: "/v1/experience/publish",
    operationId: "publishExperienceDraft",
    summary: "Publish a validated venue experience draft.",
    tags: ["Experience Studio"],
    requestBodySchema: "PublishExperienceInput",
    responseSchema: "ExperienceWorkspaceResponse",
  },
  {
    method: "patch",
    path: "/v1/experience/identity",
    operationId: "updateExperienceIdentity",
    summary: "Update the current venue business identity and draft presentation.",
    tags: ["Experience Studio"],
    requestBodySchema: "ExperienceIdentityInput",
    responseSchema: "ExperienceWorkspaceResponse",
  },
  {
    method: "get",
    path: "/v1/experience/resources",
    operationId: "listExperienceResources",
    summary: "List resources in the current venue experience, including archived entries.",
    tags: ["Experience Studio"],
    querySchema: "ListResourcesQuery",
    responseSchema: "ListResourcesResponse",
  },
  {
    method: "get",
    path: "/v1/experience/operating-hours",
    operationId: "getExperienceOperatingHours",
    summary: "Read venue operating hours and booking rules",
    tags: ["experience"],
    responseSchema: "ExperienceOperatingHoursResponse",
  },
  {
    method: "put",
    path: "/v1/experience/operating-hours",
    operationId: "updateExperienceOperatingHours",
    summary: "Replace venue operating hours and booking rules",
    tags: ["experience"],
    requestBodySchema: "ExperienceOperatingHoursInput",
    responseSchema: "ExperienceOperatingHoursResponse",
  },
  {
    method: "get",
    path: "/v1/experience/knowledge",
    operationId: "listExperienceKnowledge",
    summary: "List owner-managed experience knowledge",
    tags: ["experience"],
    responseSchema: "ListExperienceKnowledgeResponse",
  },
  {
    method: "post",
    path: "/v1/experience/knowledge",
    operationId: "createExperienceKnowledge",
    summary: "Create an experience knowledge entry",
    tags: ["experience"],
    requestBodySchema: "ExperienceKnowledgeInput",
    responseSchema: "ExperienceKnowledgeEntryResponse",
    successStatus: "201",
  },
  {
    method: "put",
    path: "/v1/experience/knowledge/{knowledge_id}",
    operationId: "updateExperienceKnowledge",
    summary: "Update an experience knowledge entry",
    tags: ["experience"],
    pathParameters: ["knowledge_id"],
    requestBodySchema: "ExperienceKnowledgeInput",
    responseSchema: "ExperienceKnowledgeEntryResponse",
  },
  {
    method: "post",
    path: "/v1/experience/knowledge/{knowledge_id}/archive",
    operationId: "archiveExperienceKnowledge",
    summary: "Archive an experience knowledge entry",
    tags: ["experience"],
    pathParameters: ["knowledge_id"],
    responseSchema: "ExperienceKnowledgeEntryResponse",
  },
  {
    method: "get",
    path: "/v1/experience/channels",
    operationId: "getExperienceChannelSettings",
    summary: "Read desired channel settings and runtime readiness",
    tags: ["experience"],
    responseSchema: "ExperienceChannelSettingsResponse",
  },
  {
    method: "put",
    path: "/v1/experience/channels",
    operationId: "updateExperienceChannelSettings",
    summary: "Update desired customer channels",
    tags: ["experience"],
    requestBodySchema: "ExperienceChannels",
    responseSchema: "ExperienceChannelSettingsResponse",
  },
  {
    method: "post",
    path: "/v1/experience/services",
    operationId: "createExperienceService",
    summary: "Create a service in the current venue experience.",
    tags: ["Experience Studio"],
    requestBodySchema: "ExperienceServiceInput",
    responseSchema: "ServiceResponse",
    successStatus: "201",
  },
  {
    method: "put",
    path: "/v1/experience/services/{service_id}",
    operationId: "updateExperienceService",
    summary: "Update a service in the current venue experience.",
    tags: ["Experience Studio"],
    pathParameters: ["service_id"],
    requestBodySchema: "ExperienceServiceInput",
    responseSchema: "ServiceResponse",
  },
  {
    method: "post",
    path: "/v1/experience/services/{service_id}/archive",
    operationId: "archiveExperienceService",
    summary: "Archive a service while preserving reservation history.",
    tags: ["Experience Studio"],
    pathParameters: ["service_id"],
    requestBodySchema: "ArchiveCatalogItemInput",
    responseSchema: "ServiceResponse",
  },
  {
    method: "post",
    path: "/v1/experience/resources",
    operationId: "createExperienceResource",
    summary: "Create a resource in the current venue experience.",
    tags: ["Experience Studio"],
    requestBodySchema: "ExperienceResourceInput",
    responseSchema: "ResourceResponse",
    successStatus: "201",
  },
  {
    method: "put",
    path: "/v1/experience/resources/{resource_id}",
    operationId: "updateExperienceResource",
    summary: "Update a resource in the current venue experience.",
    tags: ["Experience Studio"],
    pathParameters: ["resource_id"],
    requestBodySchema: "ExperienceResourceInput",
    responseSchema: "ResourceResponse",
  },
  {
    method: "post",
    path: "/v1/experience/resources/{resource_id}/archive",
    operationId: "archiveExperienceResource",
    summary: "Archive a resource while preserving reservation history.",
    tags: ["Experience Studio"],
    pathParameters: ["resource_id"],
    requestBodySchema: "ArchiveCatalogItemInput",
    responseSchema: "ResourceResponse",
  },
  {
    method: "get",
    path: "/v1/public/experiences/{slug}",
    operationId: "getPublicExperience",
    summary: "Read a published browser-safe experience by slug.",
    tags: ["Experience Studio"],
    pathParameters: ["slug"],
    responseSchema: "PublicExperienceResponse",
    authentication: "public",
  },
  {
    method: "get",
    path: "/v1/public/experiences/{slug}/services",
    operationId: "listPublicExperienceServices",
    summary: "List active services for a published booking experience.",
    tags: ["Public booking"],
    pathParameters: ["slug"],
    responseSchema: "ListServicesResponse",
    authentication: "public",
  },
  {
    method: "get",
    path: "/v1/public/experiences/{slug}/availability",
    operationId: "listPublicExperienceAvailability",
    summary: "Read availability for a service in a published booking experience.",
    tags: ["Public booking"],
    pathParameters: ["slug"],
    querySchema: "AvailabilityQuery",
    responseSchema: "AvailabilityResponse",
    authentication: "public",
  },
  {
    method: "post",
    path: "/v1/public/experiences/{slug}/reservations",
    operationId: "createPublicExperienceReservation",
    summary: "Create a reservation in a published booking experience.",
    tags: ["Public booking"],
    pathParameters: ["slug"],
    requestBodySchema: "CreateReservationInput",
    responseSchema: "ReservationResponse",
    successStatus: "201",
    idempotencyRequired: true,
    authentication: "public",
  },
  {
    method: "get",
    path: "/v1/public/experiences/{slug}/manage/{token}",
    operationId: "getManagedReservation",
    summary: "Read one reservation through an opaque customer management token.",
    tags: ["Public booking"],
    pathParameters: ["slug", "token"],
    responseSchema: "ReservationResponse",
    authentication: "public",
  },
  {
    method: "post",
    path: "/v1/public/experiences/{slug}/manage/{token}/cancel",
    operationId: "cancelManagedReservation",
    summary: "Cancel one future reservation through an opaque customer management token.",
    tags: ["Public booking"],
    pathParameters: ["slug", "token"],
    responseSchema: "ReservationResponse",
    authentication: "public",
  },
  {
    method: "post",
    path: "/v1/public/experiences/{slug}/manage/{token}/reschedule",
    operationId: "rescheduleManagedReservation",
    summary: "Reschedule one future reservation through an opaque customer management token.",
    tags: ["Public booking"],
    pathParameters: ["slug", "token"],
    requestBodySchema: "RescheduleManagedReservationInput",
    responseSchema: "ReservationResponse",
    authentication: "public",
  },
  {
    method: "get",
    path: "/v1/operations/overview",
    operationId: "getOperationsOverview",
    summary: "Read bounded venue operational counts and today's reservation timeline.",
    tags: ["Operations"],
    responseSchema: "OperationsOverviewResponse",
  },
  {
    method: "get",
    path: "/v1/analytics",
    operationId: "getAnalytics",
    summary: "Read bounded descriptive reservation and channel analytics for a venue.",
    tags: ["Analytics"],
    querySchema: "AnalyticsQuery",
    responseSchema: "AnalyticsResponse",
  },
  {
    method: "get",
    path: "/v1/conversations",
    operationId: "listConversations",
    summary: "List venue conversations for the owner inbox.",
    tags: ["Conversations"],
    querySchema: "ListConversationsQuery",
    responseSchema: "ListConversationsResponse",
  },
  {
    method: "post",
    path: "/v1/public/experiences/{slug}/chat/messages",
    operationId: "sendPublicChatMessage",
    summary: "Send a customer message through a published web-chat experience.",
    tags: ["Public chat"],
    pathParameters: ["slug"],
    requestBodySchema: "PublicChatMessageInput",
    responseSchema: "PublicChatConversationResponse",
    authentication: "public",
  },
  {
    method: "get",
    path: "/v1/public/experiences/{slug}/chat/conversations/{conversation_id}/messages",
    operationId: "listPublicChatMessages",
    summary: "Restore a published experience conversation timeline.",
    tags: ["Public chat"],
    pathParameters: ["slug", "conversation_id"],
    querySchema: "ListConversationMessagesQuery",
    responseSchema: "ListConversationMessagesResponse",
    authentication: "public",
  },
  {
    method: "post",
    path: "/v1/public/experiences/{slug}/chat/conversations/{conversation_id}/confirm",
    operationId: "confirmPublicChatBooking",
    summary: "Explicitly confirm a validated conversational booking proposal.",
    tags: ["Public chat"],
    pathParameters: ["slug", "conversation_id"],
    requestBodySchema: "PublicChatConfirmationInput",
    responseSchema: "PublicChatConversationResponse",
    authentication: "public",
  },
  {
    method: "get",
    path: "/v1/conversations/{conversation_id}",
    operationId: "getConversation",
    summary: "Read one venue conversation.",
    tags: ["Conversations"],
    pathParameters: ["conversation_id"],
    responseSchema: "ConversationResponse",
  },
  {
    method: "get",
    path: "/v1/conversations/{conversation_id}/messages",
    operationId: "listConversationMessages",
    summary: "List a conversation timeline in chronological order.",
    tags: ["Conversations"],
    pathParameters: ["conversation_id"],
    querySchema: "ListConversationMessagesQuery",
    responseSchema: "ListConversationMessagesResponse",
  },
  {
    method: "post",
    path: "/v1/conversations/{conversation_id}/messages",
    operationId: "sendConversationStaffReply",
    summary: "Append an owner-authored reply to a conversation.",
    tags: ["Conversations"],
    pathParameters: ["conversation_id"],
    requestBodySchema: "ConversationStaffReplyInput",
    responseSchema: "ConversationMessageResponse",
  },
  {
    method: "put",
    path: "/v1/conversations/{conversation_id}/automation",
    operationId: "updateConversationAutomation",
    summary: "Take over a conversation or resume automation.",
    tags: ["Conversations"],
    pathParameters: ["conversation_id"],
    requestBodySchema: "ConversationAutomationInput",
    responseSchema: "ConversationResponse",
  },
  {
    method: "get",
    path: "/v1/metadata",
    operationId: "getMetadata",
    summary: "Read platform metadata and enabled module notices.",
    tags: ["Metadata"],
    responseSchema: "MetadataResponse",
  },
  {
    method: "get",
    path: "/v1/tenants/current",
    operationId: "getCurrentTenant",
    summary: "Read the tenant resolved from request context.",
    tags: ["Tenants"],
    responseSchema: "TenantResponse",
  },
  {
    method: "get",
    path: "/v1/venues",
    operationId: "listVenues",
    summary: "List visible venues.",
    tags: ["Catalog"],
    querySchema: "ListVenuesQuery",
    responseSchema: "ListVenuesResponse",
  },
  {
    method: "get",
    path: "/v1/venues/{venue_id}",
    operationId: "getVenue",
    summary: "Read one venue by id.",
    tags: ["Catalog"],
    pathParameters: ["venue_id"],
    responseSchema: "VenueResponse",
  },
  {
    method: "get",
    path: "/v1/services",
    operationId: "listServices",
    summary: "List reservable services.",
    tags: ["Catalog"],
    querySchema: "ListServicesQuery",
    responseSchema: "ListServicesResponse",
  },
  {
    method: "get",
    path: "/v1/services/{service_id}",
    operationId: "getService",
    summary: "Read one reservable service by id.",
    tags: ["Catalog"],
    pathParameters: ["service_id"],
    responseSchema: "ServiceResponse",
  },
  {
    method: "get",
    path: "/v1/resources",
    operationId: "listResources",
    summary: "List reservable resources.",
    tags: ["Catalog"],
    querySchema: "ListResourcesQuery",
    responseSchema: "ListResourcesResponse",
  },
  {
    method: "get",
    path: "/v1/resources/{resource_id}",
    operationId: "getResource",
    summary: "Read one reservable resource by id.",
    tags: ["Catalog"],
    pathParameters: ["resource_id"],
    responseSchema: "ResourceResponse",
  },
  {
    method: "get",
    path: "/v1/resource-layouts/{layout_id}",
    operationId: "getResourceLayout",
    summary: "Read one resource layout by id.",
    tags: ["Catalog"],
    pathParameters: ["layout_id"],
    responseSchema: "ResourceLayoutResponse",
  },
  {
    method: "get",
    path: "/v1/availability",
    operationId: "listAvailability",
    summary: "List available reservation slots.",
    tags: ["Availability"],
    querySchema: "AvailabilityQuery",
    responseSchema: "AvailabilityResponse",
  },
  {
    method: "get",
    path: "/v1/reservations",
    operationId: "listReservations",
    summary: "List reservations visible to the caller.",
    tags: ["Reservations"],
    querySchema: "ListReservationsQuery",
    responseSchema: "ListReservationsResponse",
  },
  {
    method: "post",
    path: "/v1/reservations",
    operationId: "createReservation",
    summary: "Create a reservation.",
    tags: ["Reservations"],
    requestBodySchema: "CreateReservationInput",
    responseSchema: "ReservationResponse",
    successStatus: "201",
    idempotencyRequired: true,
  },
  {
    method: "get",
    path: "/v1/reservations/{reservation_id}",
    operationId: "getReservation",
    summary: "Read one reservation by id.",
    tags: ["Reservations"],
    pathParameters: ["reservation_id"],
    responseSchema: "ReservationResponse",
  },
  {
    method: "patch",
    path: "/v1/reservations/{reservation_id}",
    operationId: "updateReservation",
    summary: "Patch non-slot reservation fields.",
    tags: ["Reservations"],
    pathParameters: ["reservation_id"],
    requestBodySchema: "UpdateReservationPatch",
    responseSchema: "ReservationResponse",
    idempotencyRequired: true,
  },
  {
    method: "post",
    path: "/v1/reservations/{reservation_id}/cancel",
    operationId: "cancelReservation",
    summary: "Cancel a reservation.",
    tags: ["Reservations"],
    pathParameters: ["reservation_id"],
    requestBodySchema: "CancelReservationInput",
    responseSchema: "ReservationResponse",
    idempotencyRequired: true,
  },
  {
    method: "post",
    path: "/v1/reservations/{reservation_id}/reschedule",
    operationId: "rescheduleReservation",
    summary: "Move a reservation to another slot or resource assignment.",
    tags: ["Reservations"],
    pathParameters: ["reservation_id"],
    requestBodySchema: "RescheduleReservationInput",
    responseSchema: "ReservationResponse",
    idempotencyRequired: true,
  },
  {
    method: "get",
    path: "/v1/resource-maintenance",
    operationId: "listResourceMaintenance",
    summary: "List resource maintenance blocks.",
    tags: ["Resource maintenance"],
    querySchema: "ListResourceMaintenanceQuery",
    responseSchema: "ListResourceMaintenanceResponse",
  },
  {
    method: "post",
    path: "/v1/resource-maintenance",
    operationId: "createResourceMaintenance",
    summary: "Create a resource maintenance block.",
    tags: ["Resource maintenance"],
    requestBodySchema: "CreateResourceMaintenanceInput",
    responseSchema: "ResourceMaintenanceResponse",
    successStatus: "201",
    idempotencyRequired: true,
  },
  {
    method: "post",
    path: "/v1/resource-maintenance/{maintenance_id}/end",
    operationId: "endResourceMaintenance",
    summary: "End a resource maintenance block.",
    tags: ["Resource maintenance"],
    pathParameters: ["maintenance_id"],
    requestBodySchema: "EndResourceMaintenanceInput",
    responseSchema: "ResourceMaintenanceResponse",
    idempotencyRequired: true,
  },
  {
    method: "post",
    path: "/v1/chat/reservation-sessions",
    operationId: "createChatReservationSession",
    summary: "Create a chat reservation session when the chat module is enabled.",
    tags: ["Chat"],
    requestBodySchema: "ChatCreateReservationSessionInput",
    responseSchema: "ChatSessionResponse",
    successStatus: "201",
    idempotencyRequired: true,
    moduleGated: "chat",
    disabledErrorCode: "chat_module_disabled",
  },
  {
    method: "post",
    path: "/v1/chat/reservation-sessions/{chat_session_id}/messages",
    operationId: "sendChatMessage",
    summary: "Send a chat message when the chat module is enabled.",
    tags: ["Chat"],
    pathParameters: ["chat_session_id"],
    requestBodySchema: "ChatMessageInput",
    responseSchema: "ChatMessageResponse",
    idempotencyRequired: true,
    moduleGated: "chat",
    disabledErrorCode: "chat_module_disabled",
  },
  {
    method: "post",
    path: "/v1/chat/reservation-sessions/{chat_session_id}/messages:stream",
    operationId: "streamChatMessage",
    summary: "Stream a chat response when the chat module is enabled.",
    tags: ["Chat"],
    pathParameters: ["chat_session_id"],
    requestBodySchema: "ChatMessageInput",
    responseSchema: "ChatMessageResponse",
    idempotencyRequired: true,
    moduleGated: "chat",
    disabledErrorCode: "chat_module_disabled",
  },
  {
    method: "post",
    path: "/v1/chat/reservation-sessions/{chat_session_id}/confirm",
    operationId: "confirmChatReservation",
    summary: "Confirm a chat-prepared reservation when the chat module is enabled.",
    tags: ["Chat"],
    pathParameters: ["chat_session_id"],
    requestBodySchema: "ChatConfirmReservationInput",
    responseSchema: "ChatMessageResponse",
    idempotencyRequired: true,
    moduleGated: "chat",
    disabledErrorCode: "chat_module_disabled",
  },
];

export const publicOpenApiInfo = {
  title: "Reservation Platform API",
  version: "0.0.0",
  description: "Public /v1 reservation platform API contract generated from @reservation-platform/contract-types.",
};
