export type JsonSchema = Record<string, unknown>;

export interface ContractOperation {
  method: "get" | "post" | "patch";
  path: string;
  operationId: string;
  summary: string;
  tags: string[];
  responseSchema: string;
  successStatus?: "200" | "201";
  querySchema?: string;
  requestBodySchema?: string;
  pathParameters?: string[];
  idempotencyRequired?: boolean;
  moduleGated?: "chat";
  disabledErrorCode?: string;
}

const ref = (name: string) => ({ $ref: `#/$defs/${name}` });
const stringSchema = { type: "string" };
const booleanSchema = { type: "boolean" };
const positiveIntegerSchema = { type: "integer", minimum: 1 };
const nonNegativeIntegerSchema = { type: "integer", minimum: 0 };
const stringArraySchema = { type: "array", items: stringSchema };

const objectSchema = (
  properties: Record<string, JsonSchema>,
  required: string[] = [],
): JsonSchema => ({
  type: "object",
  properties,
  ...(required.length > 0 ? { required } : {}),
  additionalProperties: false,
});

export const publicJsonSchemaDefinitions: Record<string, JsonSchema> = {
  JsonPrimitive: {
    oneOf: [
      stringSchema,
      { type: "number" },
      booleanSchema,
      { type: "null" },
    ],
  },
  JsonValue: {
    oneOf: [
      ref("JsonPrimitive"),
      { type: "array", items: ref("JsonValue") },
      { type: "object", additionalProperties: ref("JsonValue") },
    ],
  },
  MetadataValue: ref("JsonPrimitive"),
  MetadataRecord: {
    type: "object",
    additionalProperties: ref("MetadataValue"),
  },
  RequestContext: objectSchema({
    tenant_id: stringSchema,
    venue_id: stringSchema,
    correlation_id: stringSchema,
  }),
  MetadataResponse: objectSchema({
    api_version: stringSchema,
    modules: stringArraySchema,
    compatibility: objectSchema({
      sdk_versions: stringArraySchema,
      contract_types_versions: stringArraySchema,
      notices: stringArraySchema,
    }),
  }, ["api_version", "modules"]),
  TenantResponse: objectSchema({
    tenant_id: stringSchema,
    name: stringSchema,
    default_venue_id: stringSchema,
    metadata: ref("MetadataRecord"),
  }, ["tenant_id"]),
  ListVenuesQuery: objectSchema({
    tenant_id: stringSchema,
    include_inactive: booleanSchema,
  }),
  VenueResponse: objectSchema({
    venue_id: stringSchema,
    tenant_id: stringSchema,
    name: stringSchema,
    timezone: stringSchema,
    metadata: ref("MetadataRecord"),
  }, ["venue_id", "name"]),
  ListVenuesResponse: objectSchema({
    venues: { type: "array", items: ref("VenueResponse") },
  }, ["venues"]),
  ListServicesQuery: objectSchema({
    venue_id: stringSchema,
    include_inactive: booleanSchema,
  }),
  ResourceKind: {
    type: "string",
    enum: ["seat", "station", "room", "court", "screening", "capacity_bucket", "custom"],
  },
  ResourceStrategy: {
    type: "string",
    enum: ["quantity", "assigned_resource", "hybrid"],
  },
  ResourceResponse: objectSchema({
    resource_id: stringSchema,
    service_id: stringSchema,
    label: stringSchema,
    kind: ref("ResourceKind"),
    is_active: booleanSchema,
    capacity: nonNegativeIntegerSchema,
    metadata: ref("MetadataRecord"),
  }, ["resource_id", "label", "kind", "is_active"]),
  ResourceLayoutResource: objectSchema({
    resource_id: stringSchema,
    label: stringSchema,
    row: { type: "integer" },
    column: { type: "integer" },
    x: { type: "number" },
    y: { type: "number" },
    width: { type: "number", exclusiveMinimum: 0 },
    height: { type: "number", exclusiveMinimum: 0 },
    metadata: ref("MetadataRecord"),
  }, ["resource_id"]),
  ResourceLayoutResponse: objectSchema({
    layout_id: stringSchema,
    service_id: stringSchema,
    kind: { type: "string", enum: ["none", "grid", "custom"] },
    resources: { type: "array", items: ref("ResourceLayoutResource") },
    metadata: ref("MetadataRecord"),
  }, ["layout_id", "kind"]),
  ServiceResponse: objectSchema({
    service_id: stringSchema,
    venue_id: stringSchema,
    name: stringSchema,
    description: stringSchema,
    duration_minutes: positiveIntegerSchema,
    total_quantity: nonNegativeIntegerSchema,
    resource_kind: ref("ResourceKind"),
    resource_strategy: ref("ResourceStrategy"),
    reservation_policy: ref("JsonValue"),
    resources: { type: "array", items: ref("ResourceResponse") },
    layout: ref("ResourceLayoutResponse"),
    metadata: ref("MetadataRecord"),
  }, ["service_id", "name"]),
  ListServicesResponse: objectSchema({
    services: { type: "array", items: ref("ServiceResponse") },
  }, ["services"]),
  ListResourcesQuery: objectSchema({
    venue_id: stringSchema,
    service_id: stringSchema,
    include_inactive: booleanSchema,
  }),
  ListResourcesResponse: objectSchema({
    resources: { type: "array", items: ref("ResourceResponse") },
  }, ["resources"]),
  AvailabilityQuery: objectSchema({
    venue_id: stringSchema,
    service_id: stringSchema,
    date: stringSchema,
    start_at: stringSchema,
    end_at: stringSchema,
    quantity: positiveIntegerSchema,
    resource_ids: stringArraySchema,
  }, ["service_id"]),
  AvailabilitySlot: objectSchema({
    start_at: stringSchema,
    end_at: stringSchema,
    start_time: stringSchema,
    end_time: stringSchema,
    available_quantity: nonNegativeIntegerSchema,
    is_available: booleanSchema,
    resource_ids: stringArraySchema,
    taken_resource_labels: stringArraySchema,
    maintenance_resource_labels: stringArraySchema,
  }, ["available_quantity", "is_available"]),
  AvailabilityResponse: objectSchema({
    slots: { type: "array", items: ref("AvailabilitySlot") },
    total_quantity: nonNegativeIntegerSchema,
    resource_kind: ref("ResourceKind"),
    resource_strategy: ref("ResourceStrategy"),
    reservation_policy: ref("JsonValue"),
    resources: { type: "array", items: ref("ResourceResponse") },
    layout: ref("ResourceLayoutResponse"),
  }, ["slots"]),
  CustomerSnapshot: objectSchema({
    customer_id: stringSchema,
    external_customer_id: stringSchema,
    name: stringSchema,
    email: stringSchema,
    phone: stringSchema,
    locale: stringSchema,
    metadata: ref("MetadataRecord"),
  }),
  ReservationItemInput: objectSchema({
    resource_id: stringSchema,
    resource_label: stringSchema,
    quantity: positiveIntegerSchema,
  }, ["quantity"]),
  PaymentReference: objectSchema({
    payment_reference_id: stringSchema,
    provider: stringSchema,
    status: stringSchema,
    metadata: ref("MetadataRecord"),
  }),
  CreateReservationInput: objectSchema({
    tenant_id: stringSchema,
    venue_id: stringSchema,
    service_id: stringSchema,
    start_at: stringSchema,
    end_at: stringSchema,
    date: stringSchema,
    start_time: stringSchema,
    end_time: stringSchema,
    quantity: positiveIntegerSchema,
    resource_ids: stringArraySchema,
    reservation_items: { type: "array", items: ref("ReservationItemInput") },
    customer: ref("CustomerSnapshot"),
    source: stringSchema,
    metadata: ref("MetadataRecord"),
    payment_reference: ref("PaymentReference"),
  }, ["service_id", "quantity", "customer"]),
  ReservationResponse: objectSchema({
    reservation_id: stringSchema,
    status: stringSchema,
    tenant_id: stringSchema,
    venue_id: stringSchema,
    service_id: stringSchema,
    start_at: stringSchema,
    end_at: stringSchema,
    date: stringSchema,
    start_time: stringSchema,
    end_time: stringSchema,
    quantity: positiveIntegerSchema,
    reservation_items: { type: "array", items: ref("ReservationItemInput") },
    customer: ref("CustomerSnapshot"),
    payment_reference: ref("PaymentReference"),
    metadata: ref("MetadataRecord"),
    created_at: stringSchema,
    updated_at: stringSchema,
  }, ["reservation_id", "status", "service_id", "quantity"]),
  ListReservationsQuery: objectSchema({
    tenant_id: stringSchema,
    venue_id: stringSchema,
    service_id: stringSchema,
    status: stringSchema,
    customer_id: stringSchema,
    start_at: stringSchema,
    end_at: stringSchema,
  }),
  ReservationListSummary: objectSchema({
    total: nonNegativeIntegerSchema,
    confirmed_today: nonNegativeIntegerSchema,
  }),
  ListReservationsResponse: objectSchema({
    reservations: { type: "array", items: ref("ReservationResponse") },
    summary: ref("ReservationListSummary"),
  }, ["reservations"]),
  UpdateReservationPatch: objectSchema({
    customer: ref("CustomerSnapshot"),
    notes: stringSchema,
    metadata: ref("MetadataRecord"),
    status: stringSchema,
    source: stringSchema,
    payment_reference: ref("PaymentReference"),
  }),
  CancelReservationInput: objectSchema({
    reason: stringSchema,
    metadata: ref("MetadataRecord"),
  }),
  RescheduleReservationInput: objectSchema({
    start_at: stringSchema,
    end_at: stringSchema,
    date: stringSchema,
    start_time: stringSchema,
    end_time: stringSchema,
    quantity: positiveIntegerSchema,
    resource_ids: stringArraySchema,
    reservation_items: { type: "array", items: ref("ReservationItemInput") },
    metadata: ref("MetadataRecord"),
  }),
  ListResourceMaintenanceQuery: objectSchema({
    venue_id: stringSchema,
    service_id: stringSchema,
    resource_id: stringSchema,
    active_only: booleanSchema,
  }),
  ResourceMaintenanceResponse: objectSchema({
    maintenance_id: stringSchema,
    resource_id: stringSchema,
    service_id: stringSchema,
    starts_at: stringSchema,
    ends_at: stringSchema,
    reason: stringSchema,
    metadata: ref("MetadataRecord"),
  }, ["maintenance_id"]),
  ListResourceMaintenanceResponse: objectSchema({
    maintenance: { type: "array", items: ref("ResourceMaintenanceResponse") },
  }, ["maintenance"]),
  CreateResourceMaintenanceInput: objectSchema({
    resource_id: stringSchema,
    service_id: stringSchema,
    starts_at: stringSchema,
    ends_at: stringSchema,
    reason: stringSchema,
    metadata: ref("MetadataRecord"),
  }),
  EndResourceMaintenanceInput: objectSchema({
    ended_at: stringSchema,
    reason: stringSchema,
    metadata: ref("MetadataRecord"),
  }),
  PlatformErrorCode: {
    type: "string",
    description: "Stable machine-readable platform error code. Known codes include bad_request, unauthorized, forbidden, not_found, conflict, validation_failed, missing_idempotency_key, idempotency_key_reused_with_different_request, idempotency_replay_unavailable, and chat_module_disabled.",
  },
  IdempotencyMetadata: objectSchema({
    key: stringSchema,
    status: { type: "string", enum: ["created", "replayed", "rejected"] },
    replayed: booleanSchema,
  }),
  PlatformErrorBody: objectSchema({
    code: ref("PlatformErrorCode"),
    message: stringSchema,
    status: { type: "integer" },
    request_id: stringSchema,
    details: ref("JsonValue"),
    causes: { type: "array", items: ref("JsonValue") },
    retryable: booleanSchema,
    idempotency: ref("IdempotencyMetadata"),
    documentation_url: stringSchema,
  }, ["code", "message", "status"]),
  PlatformErrorResponse: objectSchema({
    error: ref("PlatformErrorBody"),
  }, ["error"]),
  ChatCreateReservationSessionInput: objectSchema({
    customer: ref("CustomerSnapshot"),
    service_id: stringSchema,
    venue_id: stringSchema,
    metadata: ref("MetadataRecord"),
  }),
  ChatSessionResponse: objectSchema({
    chat_session_id: stringSchema,
    status: stringSchema,
    metadata: ref("MetadataRecord"),
  }, ["chat_session_id", "status"]),
  ChatMessageInput: objectSchema({
    message: stringSchema,
    metadata: ref("MetadataRecord"),
  }, ["message"]),
  ChatMessageResponse: objectSchema({
    chat_session_id: stringSchema,
    message_id: stringSchema,
    content: stringSchema,
    actions: { type: "array", items: ref("JsonValue") },
    reservation: ref("ReservationResponse"),
    metadata: ref("MetadataRecord"),
  }, ["chat_session_id"]),
  ChatConfirmReservationInput: objectSchema({
    reservation_intent_id: stringSchema,
    metadata: ref("MetadataRecord"),
  }),
};

export const publicContractOperations: ContractOperation[] = [
  {
    method: "get",
    path: "/v1/metadata",
    operationId: "getMetadata",
    summary: "Read platform metadata and enabled module notices.",
    tags: ["Metadata"],
    responseSchema: "MetadataResponse",
  },
  {
    method: "get",
    path: "/v1/tenants/current",
    operationId: "getCurrentTenant",
    summary: "Read the tenant resolved from request context.",
    tags: ["Tenants"],
    responseSchema: "TenantResponse",
  },
  {
    method: "get",
    path: "/v1/venues",
    operationId: "listVenues",
    summary: "List visible venues.",
    tags: ["Catalog"],
    querySchema: "ListVenuesQuery",
    responseSchema: "ListVenuesResponse",
  },
  {
    method: "get",
    path: "/v1/venues/{venue_id}",
    operationId: "getVenue",
    summary: "Read one venue by id.",
    tags: ["Catalog"],
    pathParameters: ["venue_id"],
    responseSchema: "VenueResponse",
  },
  {
    method: "get",
    path: "/v1/services",
    operationId: "listServices",
    summary: "List reservable services.",
    tags: ["Catalog"],
    querySchema: "ListServicesQuery",
    responseSchema: "ListServicesResponse",
  },
  {
    method: "get",
    path: "/v1/services/{service_id}",
    operationId: "getService",
    summary: "Read one reservable service by id.",
    tags: ["Catalog"],
    pathParameters: ["service_id"],
    responseSchema: "ServiceResponse",
  },
  {
    method: "get",
    path: "/v1/resources",
    operationId: "listResources",
    summary: "List reservable resources.",
    tags: ["Catalog"],
    querySchema: "ListResourcesQuery",
    responseSchema: "ListResourcesResponse",
  },
  {
    method: "get",
    path: "/v1/resources/{resource_id}",
    operationId: "getResource",
    summary: "Read one reservable resource by id.",
    tags: ["Catalog"],
    pathParameters: ["resource_id"],
    responseSchema: "ResourceResponse",
  },
  {
    method: "get",
    path: "/v1/resource-layouts/{layout_id}",
    operationId: "getResourceLayout",
    summary: "Read one resource layout by id.",
    tags: ["Catalog"],
    pathParameters: ["layout_id"],
    responseSchema: "ResourceLayoutResponse",
  },
  {
    method: "get",
    path: "/v1/availability",
    operationId: "listAvailability",
    summary: "List available reservation slots.",
    tags: ["Availability"],
    querySchema: "AvailabilityQuery",
    responseSchema: "AvailabilityResponse",
  },
  {
    method: "get",
    path: "/v1/reservations",
    operationId: "listReservations",
    summary: "List reservations visible to the caller.",
    tags: ["Reservations"],
    querySchema: "ListReservationsQuery",
    responseSchema: "ListReservationsResponse",
  },
  {
    method: "post",
    path: "/v1/reservations",
    operationId: "createReservation",
    summary: "Create a reservation.",
    tags: ["Reservations"],
    requestBodySchema: "CreateReservationInput",
    responseSchema: "ReservationResponse",
    successStatus: "201",
    idempotencyRequired: true,
  },
  {
    method: "get",
    path: "/v1/reservations/{reservation_id}",
    operationId: "getReservation",
    summary: "Read one reservation by id.",
    tags: ["Reservations"],
    pathParameters: ["reservation_id"],
    responseSchema: "ReservationResponse",
  },
  {
    method: "patch",
    path: "/v1/reservations/{reservation_id}",
    operationId: "updateReservation",
    summary: "Patch non-slot reservation fields.",
    tags: ["Reservations"],
    pathParameters: ["reservation_id"],
    requestBodySchema: "UpdateReservationPatch",
    responseSchema: "ReservationResponse",
    idempotencyRequired: true,
  },
  {
    method: "post",
    path: "/v1/reservations/{reservation_id}/cancel",
    operationId: "cancelReservation",
    summary: "Cancel a reservation.",
    tags: ["Reservations"],
    pathParameters: ["reservation_id"],
    requestBodySchema: "CancelReservationInput",
    responseSchema: "ReservationResponse",
    idempotencyRequired: true,
  },
  {
    method: "post",
    path: "/v1/reservations/{reservation_id}/reschedule",
    operationId: "rescheduleReservation",
    summary: "Move a reservation to another slot or resource assignment.",
    tags: ["Reservations"],
    pathParameters: ["reservation_id"],
    requestBodySchema: "RescheduleReservationInput",
    responseSchema: "ReservationResponse",
    idempotencyRequired: true,
  },
  {
    method: "get",
    path: "/v1/resource-maintenance",
    operationId: "listResourceMaintenance",
    summary: "List resource maintenance blocks.",
    tags: ["Resource maintenance"],
    querySchema: "ListResourceMaintenanceQuery",
    responseSchema: "ListResourceMaintenanceResponse",
  },
  {
    method: "post",
    path: "/v1/resource-maintenance",
    operationId: "createResourceMaintenance",
    summary: "Create a resource maintenance block.",
    tags: ["Resource maintenance"],
    requestBodySchema: "CreateResourceMaintenanceInput",
    responseSchema: "ResourceMaintenanceResponse",
    successStatus: "201",
    idempotencyRequired: true,
  },
  {
    method: "post",
    path: "/v1/resource-maintenance/{maintenance_id}/end",
    operationId: "endResourceMaintenance",
    summary: "End a resource maintenance block.",
    tags: ["Resource maintenance"],
    pathParameters: ["maintenance_id"],
    requestBodySchema: "EndResourceMaintenanceInput",
    responseSchema: "ResourceMaintenanceResponse",
    idempotencyRequired: true,
  },
  {
    method: "post",
    path: "/v1/chat/reservation-sessions",
    operationId: "createChatReservationSession",
    summary: "Create a chat reservation session when the chat module is enabled.",
    tags: ["Chat"],
    requestBodySchema: "ChatCreateReservationSessionInput",
    responseSchema: "ChatSessionResponse",
    successStatus: "201",
    idempotencyRequired: true,
    moduleGated: "chat",
    disabledErrorCode: "chat_module_disabled",
  },
  {
    method: "post",
    path: "/v1/chat/reservation-sessions/{chat_session_id}/messages",
    operationId: "sendChatMessage",
    summary: "Send a chat message when the chat module is enabled.",
    tags: ["Chat"],
    pathParameters: ["chat_session_id"],
    requestBodySchema: "ChatMessageInput",
    responseSchema: "ChatMessageResponse",
    idempotencyRequired: true,
    moduleGated: "chat",
    disabledErrorCode: "chat_module_disabled",
  },
  {
    method: "post",
    path: "/v1/chat/reservation-sessions/{chat_session_id}/messages:stream",
    operationId: "streamChatMessage",
    summary: "Stream a chat response when the chat module is enabled.",
    tags: ["Chat"],
    pathParameters: ["chat_session_id"],
    requestBodySchema: "ChatMessageInput",
    responseSchema: "ChatMessageResponse",
    idempotencyRequired: true,
    moduleGated: "chat",
    disabledErrorCode: "chat_module_disabled",
  },
  {
    method: "post",
    path: "/v1/chat/reservation-sessions/{chat_session_id}/confirm",
    operationId: "confirmChatReservation",
    summary: "Confirm a chat-prepared reservation when the chat module is enabled.",
    tags: ["Chat"],
    pathParameters: ["chat_session_id"],
    requestBodySchema: "ChatConfirmReservationInput",
    responseSchema: "ChatMessageResponse",
    idempotencyRequired: true,
    moduleGated: "chat",
    disabledErrorCode: "chat_module_disabled",
  },
];

export const publicOpenApiInfo = {
  title: "Reservation Platform API",
  version: "0.0.0",
  description: "Public /v1 reservation platform API contract generated from @reservation-platform/contract-types.",
};
