db-uri = "@/run/reservation-secrets/database-uri"
db-schemas = "public"
db-anon-role = "anon"
jwt-secret = "@/run/reservation-secrets/postgrest-jwt-secret"
jwt-aud = "postgrest"
server-host = "0.0.0.0"
server-port = 3000
admin-server-host = "127.0.0.1"
admin-server-port = 3001
admin-server-config-enabled = false
db-config = false
log-level = "error"
