services:
  studio:
    ports: !override
      - "127.0.0.1:3000:3000/tcp"

  kong:
    ports: !override
      - "127.0.0.1:${KONG_HTTP_PORT}:8000/tcp"
      - "127.0.0.1:${KONG_HTTPS_PORT}:8443/tcp"

  supavisor:
    ports: !override
      - "127.0.0.1:${POSTGRES_PORT}:5432/tcp"
      - "127.0.0.1:${POOLER_PROXY_PORT_TRANSACTION}:6543/tcp"
